#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=11

# ── Local helpers (the library above the marker is untouched) ─────────────

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$REPO/backend/.env"   # so existing values are offered as defaults

# vercel_env DIR NAME VALUE — upsert a production env var on one project.
# Remove-then-add because `vercel env add` refuses to overwrite.
vercel_env() {
  local dir="$1" name="$2" value="$3"
  if [[ -z "$value" ]]; then note "skipped $name (no value given)"; return 0; fi
  ( cd "$REPO/$dir" && vercel env rm "$name" production --yes >/dev/null 2>&1 ) || true
  if ( cd "$REPO/$dir" && printf '%s' "$value" | vercel env add "$name" production >/dev/null 2>&1 ); then
    printf '  %s✓ set%s %s on the %s project\n' "$GREEN" "$RESET" "$name" "$dir"
  else
    SKIPPED+=("Vercel env $name on $dir")
    warn "could not set $name on $dir; do it with: cd $dir && vercel env add $name production"
  fi
}

# json_field FILE KEY — pull one string field out of a small JSON file.
json_field() {
  python3 -c "import json,sys;print(json.load(open(sys.argv[1])).get(sys.argv[2],''))" "$1" "$2" 2>/dev/null || true
}

banner "VoltPilot → Vercel deployment setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
say "Checking the tools and the two Vercel projects you already created."
ok=1
for c in gh vercel node python3 git; do
  if command -v "$c" >/dev/null 2>&1; then printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$c"
  else printf '  %s✗%s %s is missing\n' "$RED" "$RESET" "$c"; ok=0; fi
done
if gh auth status >/dev/null 2>&1; then printf '  %s✓%s gh is logged in\n' "$GREEN" "$RESET"
else printf '  %s✗%s gh is not logged in — run: gh auth login\n' "$RED" "$RESET"; ok=0; fi
for d in backend frontend; do
  if [[ -f "$REPO/$d/.vercel/project.json" ]]; then printf '  %s✓%s %s is linked to a Vercel project\n' "$GREEN" "$RESET" "$d"
  else printf '  %s✗%s %s is not linked — run: cd %s && vercel link\n' "$RED" "$RESET" "$d" "$d"; ok=0; fi
done
if [[ "$ok" -ne 1 ]]; then warn "fix the above, then re-run this script."; exit 1; fi
pause "All good. Press Enter."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Vercel: access token"
say "CI needs a token to deploy on your behalf. This is the only value you"
say "have to fetch by hand — everything else is read from your project files."
open_url "https://vercel.com/account/settings/tokens"
step "Click 'Create Token'."
step "Name it 'github-actions', scope it to your account, expiry as you like."
step "Click Create, then copy the token — it is shown only once."
ask_secret VERCEL_TOKEN "Paste the Vercel token (input hidden):"
if [[ -z "${VERCEL_TOKEN:-}" ]]; then warn "no token entered; CI deploys will fail until you set it."
else set_secret VERCEL_TOKEN "$VERCEL_TOKEN"; fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "GitHub: Vercel project IDs"
say "Reading these straight out of the .vercel/project.json files that"
say "'vercel link' created — nothing for you to copy."
ORG_ID=$(json_field "$REPO/backend/.vercel/project.json" orgId)
BE_ID=$(json_field "$REPO/backend/.vercel/project.json" projectId)
FE_ID=$(json_field "$REPO/frontend/.vercel/project.json" projectId)
note "org      $ORG_ID"
note "backend  $BE_ID"
note "frontend $FE_ID"
set_secret VERCEL_ORG_ID "$ORG_ID"
set_secret VERCEL_BACKEND_PROJECT_ID "$BE_ID"
set_secret VERCEL_FRONTEND_PROJECT_ID "$FE_ID"
pause "Press Enter."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Database: connection string"
say "Your managed Postgres URL. CI runs migrations and the daily sync against"
say "it, and the backend reads from it at runtime, so it goes to both places."
note "If backend/.env already has it, press Enter to keep that value."
open_url "https://console.neon.tech/"
step "Neon → your project → Connection Details → copy the connection string."
step "It must start postgresql+asyncpg:// for this app (not postgres://)."
ask_secret DATABASE_URL "Paste DATABASE_URL (hidden):"
if [[ -n "${DATABASE_URL:-}" ]]; then
  set_secret DATABASE_URL "$DATABASE_URL"
  vercel_env backend DATABASE_URL "$DATABASE_URL"
else
  warn "no database URL; the deploy will fail at the migration step."
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Gemini: API keys"
say "Comma-separated. The analyst walks the list and rotates to the next key"
say "when one hits its daily quota."
note "If backend/.env already has them, press Enter to keep that value."
open_url "https://aistudio.google.com/apikey"
step "Copy each key, and join them with commas: key1,key2,key3"
ask_secret GEMINI_API_KEYS "Paste GEMINI_API_KEYS (hidden):"
vercel_env backend GEMINI_API_KEYS "${GEMINI_API_KEYS:-}"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Backend: runtime settings"
say "Two fixed values, no input needed."
note "RUN_MIGRATIONS=0 — a serverless function cold-starts concurrently, so"
note "migrating on the request path would race. CI migrates once instead."
note "ENV=production — drops the localhost CORS origins."
vercel_env backend RUN_MIGRATIONS "0"
vercel_env backend ENV "production"
# The bundle is ~744 MB against a 500 MB standard limit, so it deploys as a
# Large Function (up to 5 GB on Fluid compute).
vercel_env backend VERCEL_SUPPORT_LARGE_FUNCTIONS "1"
pause "Press Enter."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Email: SMTP for the PDF report"
say "Used to send the PDF report. Skip with Enter if you don't need it yet."
ask SMTP_HOST "SMTP host (e.g. smtp.gmail.com):"
if [[ -n "${SMTP_HOST:-}" ]]; then
  ask SMTP_USER "SMTP username:"
  ask_secret SMTP_PASSWORD "SMTP password / app password (hidden):"
  ask SMTP_FROM "From address:"
  vercel_env backend SMTP_HOST "$SMTP_HOST"
  vercel_env backend SMTP_USER "${SMTP_USER:-}"
  vercel_env backend SMTP_PASSWORD "${SMTP_PASSWORD:-}"
  vercel_env backend SMTP_FROM "${SMTP_FROM:-}"
else
  note "skipped — the report endpoint will fail until these are set."
  SKIPPED+=("SMTP_* on the backend project")
fi

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "First backend deploy"
say "This proves the Python bundle builds and gives us its URL, which the"
say "frontend needs baked into its build."
if confirm "Deploy the backend now?"; then
  # Not a plain `vercel deploy`: that uploads only backend/, so the build
  # cannot reach ../data. Build in the full checkout, then upload the output.
  # --archive=tgz because the bundle is ~16,000 files against a 15,000 limit.
  BACKEND_URL=$( cd "$REPO/backend" \
    && VERCEL_SUPPORT_LARGE_FUNCTIONS=1 vercel build --prod >/dev/null 2>&1 \
    && vercel deploy --prebuilt --prod --yes --archive=tgz 2>/dev/null | tail -n1 ) || BACKEND_URL=""
  say "Vercel reported: ${BACKEND_URL:-<nothing>}"
else
  BACKEND_URL=""
fi
ask BACKEND_URL_INPUT "Backend URL (Enter accepts the one above):"
BACKEND_URL="${BACKEND_URL_INPUT:-$BACKEND_URL}"
if [[ -n "${BACKEND_URL:-}" ]]; then
  set_var BACKEND_URL "$BACKEND_URL"
  vercel_env frontend BACKEND_URL "$BACKEND_URL"
else
  warn "without BACKEND_URL the frontend build fails by design, rather than shipping a dead host."
  SKIPPED+=("BACKEND_URL GitHub variable + frontend env")
fi

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "First frontend deploy"
say "Deploys the site, then points the backend's CORS at it."
if confirm "Deploy the frontend now?"; then
  FRONTEND_ORIGIN=$( cd "$REPO/frontend" && vercel deploy --prod --yes 2>/dev/null | tail -n1 ) || FRONTEND_ORIGIN=""
  say "Vercel reported: ${FRONTEND_ORIGIN:-<nothing>}"
else
  FRONTEND_ORIGIN=""
fi
ask FRONTEND_ORIGIN_INPUT "Frontend URL (Enter accepts the one above):"
FRONTEND_ORIGIN="${FRONTEND_ORIGIN_INPUT:-$FRONTEND_ORIGIN}"
vercel_env backend FRONTEND_ORIGIN "${FRONTEND_ORIGIN:-}"

# ── 10 ────────────────────────────────────────────────────────────────────
stage "GitHub: let Actions commit the daily refresh"
say "The daily job refreshes the data files and commits them. Without write"
say "permission it still updates the database, but cannot push the files."
open_url "https://github.com/skylightlim/voltpilot/settings/actions"
step "Scroll to 'Workflow permissions'."
step "Select 'Read and write permissions'."
step "Click Save."
pause "Done? Press Enter."

# ── 11 ────────────────────────────────────────────────────────────────────
stage "Verify"
say "Checking what is actually configured."
if [[ -n "${BACKEND_URL:-}" ]]; then
  code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 30 "${BACKEND_URL%/}/health" || true)
  if [[ "$code" == "200" ]]; then printf '  %s✓%s backend /health → 200\n' "$GREEN" "$RESET"
  else printf '  %s⚠%s backend /health → %s (a cold start can take a minute; retry)\n' "$YELLOW" "$RESET" "${code:-no response}"; fi
fi
say ""
say "Secrets now on the repository:"
gh secret list 2>/dev/null | sed 's/^/    /' || note "  (could not list)"
say "Variables:"
gh variable list 2>/dev/null | sed 's/^/    /' || note "  (could not list)"

finish

printf '  %sLast step, when you are ready to ship:%s\n' "$BOLD" "$RESET"
printf '    cd %s\n' "$REPO"
printf '    git add -A && git commit -m "Deploy on Vercel; daily refresh in Actions"\n'
printf '    git push && gh run watch\n\n'
