"""initial schema

Revision ID: 27a6d6aef384
Revises: 
Create Date: 2026-09-07 00:51:51.194185
"""
from alembic import op
import sqlalchemy as sa


revision = '27a6d6aef384'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(length=200), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('fallback', sa.Text(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('price_rm', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('as_of_date', sa.String(length=20), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalog_price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_price_history_slug'), ['slug'], unique=False)

    op.create_table('catalog_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('brand', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('variant', sa.String(length=60), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('price_rm', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('as_of_date', sa.String(length=20), nullable=False),
    sa.Column('ckd', sa.Boolean(), nullable=False),
    sa.Column('specs', sa.JSON(), nullable=False),
    sa.Column('ownership', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', 'variant', name='uq_vehicle_slug_variant')
    )
    with op.batch_alter_table('catalog_vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_vehicles_slug'), ['slug'], unique=False)

    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_token', sa.String(length=40), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_result_token'), ['result_token'], unique=False)

    op.create_table('engine_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_token', sa.String(length=40), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('scores_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engine_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engine_scores_result_token'), ['result_token'], unique=False)

    op.create_table('external_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('as_of_date', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('external_factors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_factors_key'), ['key'], unique=False)

    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=40), nullable=False),
    sa.Column('profile_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profiles_token'), ['token'], unique=True)

    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_token', sa.String(length=40), nullable=False),
    sa.Column('analyst_json', sa.JSON(), nullable=False),
    sa.Column('mock', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_result_token'), ['result_token'], unique=True)

    op.create_table('report_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_token', sa.String(length=40), nullable=False),
    sa.Column('sent_to_email', sa.String(length=200), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('send_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_requests_result_token'), ['result_token'], unique=True)

    op.create_table('topsis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_token', sa.String(length=40), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('ranking_json', sa.JSON(), nullable=False),
    sa.Column('engine_scores_json', sa.JSON(), nullable=False),
    sa.Column('overview_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topsis_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topsis_results_result_token'), ['result_token'], unique=True)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('topsis_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topsis_results_result_token'))

    op.drop_table('topsis_results')
    with op.batch_alter_table('report_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_requests_result_token'))

    op.drop_table('report_requests')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_result_token'))

    op.drop_table('recommendations')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profiles_token'))

    op.drop_table('profiles')
    with op.batch_alter_table('external_factors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_factors_key'))

    op.drop_table('external_factors')
    with op.batch_alter_table('engine_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engine_scores_result_token'))

    op.drop_table('engine_scores')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_result_token'))

    op.drop_table('chat_sessions')
    with op.batch_alter_table('catalog_vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_vehicles_slug'))

    op.drop_table('catalog_vehicles')
    with op.batch_alter_table('catalog_price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_price_history_slug'))

    op.drop_table('catalog_price_history')
    op.drop_table('blocked_sites')
    # ### end Alembic commands ###
